// src/components/layout/HeaderBar.tsx
import { Button } from "@/components/ui/button";
import { IconBrandDiscordFilled, IconBrandGithubFilled } from "@tabler/icons-react";
import { useEffect, useState } from "react";
import ColorModeToggle from "./ColorModeToggle";

const appName = import.meta.env.VITE_APP_NAME;

export default function HeaderBar() {
	const [stuck, setStuck] = useState(false);

	useEffect(() => {
		const update = () => setStuck(window.scrollY > 0);
		update();
		window.addEventListener("scroll", update, { passive: true });
		return () => window.removeEventListener("scroll", update);
	}, []);

	return (
		<>
			<header
				className={
					"fixed top-0 left-0 right-0 z-10 w-full p-3 flex items-center justify-between transition-all duration-300 border-b " +
					(stuck
						? "border-border bg-[color-mix(in_oklab,var(--background)_70%,transparent)] backdrop-blur-md"
						: "border-transparent bg-transparent")
				}
			>
				<a
					href="/"
					className="ml-2 font-medium text-foreground no-underline"
				>
					<span className="text-xl font-semibold">{appName}</span>
				</a>
				<div className="flex items-center gap-2">
					<a
						href="https://nexus.qnapl.us"
						target="_blank"
						rel="noreferrer"
						aria-label="Discord"
					>
						<Button size="icon" variant="ghost" aria-label="Discord">
							<IconBrandDiscordFilled size={18} />
						</Button>
					</a>
					<a
						href="https://github.com/qnaplus"
						target="_blank"
						rel="noreferrer"
						aria-label="GitHub"
					>
						<Button size="icon" variant="ghost" aria-label="GitHub">
							<IconBrandGithubFilled size={18} />
						</Button>
					</a>
					<ColorModeToggle />
				</div>
			</header>
			<div className="p-3" />
		</>
	);
}

// src/components/shared/HeaderBar.vue
<script setup lang="ts">
import { useEventListener } from "@vueuse/core";
import { onMounted, ref } from "vue";
const header = ref<HTMLDivElement | null>(null);
const filler = ref<HTMLDivElement | null>(null);
const update = () => {
	if (window.scrollY !== 0) {
		header.value?.classList.add("header-sticky");
		header.value?.classList.remove("border-transparent");
		filler.value?.classList.remove("hidden");
	} else {
		header.value?.classList.remove("header-sticky");
		header.value?.classList.add("border-transparent");
		filler.value?.classList.add("hidden");
	}
};
onMounted(() => update());
useEventListener(document, "scroll", () => update());
const appname = import.meta.env.VITE_APP_NAME;
</script>

<template>
	<div ref="filler" class="p-3 border-b border-transparent hidden">
		<div class="p-3"></div>
	</div>
	<div ref="header"
		class="flex w-full z-10 items-center justify-between gap-5 p-3 duration-300 transition-colors border-b border-transparent">
		<a href="/" class="text-color ml-2 font-semibold">{{ appname }}</a>
		<div class="flex gap-2">
			<Button as="a" href="https://nexus.qnapl.us" target="_blank" class="header-btn" icon="pi pi-discord"
				aria-label="Discord Server" text />
			<Button as="a" href="https://github.com/qnaplus" target="_blank" class="header-btn" icon="pi pi-github"
				aria-label="Github" text />
		</div>
	</div>
</template>

<style scoped>
@reference "../../styles.css";

.header-sticky {
	position: fixed;
	top: 0;
	@apply border-surface-800 backdrop-blur-lg bg-surface-950/30;
}

.header-btn {
	width: 32px !important;
	height: 32px !important;
}

.border-b-1 {
	border-bottom-width: 1px;
}
</style>
