// src/components/question/ProgramTag.tsx
import { Badge } from "@/components/ui/badge";

type Props = {
	program: string;
};

const COLOR_MAP: Record<string, string> = {
	v5rc: "#f84f4f",
	vurc: "#9571ca",
	viqrc: "#4894f7",
	judging: "#f5ad42",
};

const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export default function ProgramTag({ program }: Props) {
	const key = program.toLowerCase();
	const color = COLOR_MAP[key] ?? "#9ca3af";
	return (
		<Badge
			style={{
				backgroundColor: `color-mix(in srgb, ${color}, transparent 84%)`,
				color,
			}}
		>
			{capitalize(program)}
		</Badge>
	);
}

// src/components/shared/ProgramTag.vue
<script setup lang="ts">
import { capitalize } from "vue";

const { program } = defineProps<{ program: string }>();
</script>

<template>
    <Tag :class="program.toLowerCase()">{{ capitalize(program) }}</Tag>
</template>

<style lang="scss">
.v5rc {
    background-color: color-mix(in srgb, #f84f4f, transparent 84%) !important;
    color: #f84f4f !important;
}

.vurc {
    background-color: color-mix(in srgb, #9571ca, transparent 84%) !important;
    color: #9571ca !important;
}

.viqrc {
    background-color: color-mix(in srgb, #4894f7, transparent 84%) !important;
    color: #4894f7 !important;
}

.judging {
    background-color: color-mix(in srgb, #f5ad42, transparent 84%) !important;
    color: #f5ad42 !important;
}
</style>
