// src/components/question/QuestionTags.tsx
import { Badge } from "@/components/ui/badge";
import ProgramTag from "./ProgramTag";

type Props = {
	tags: string[];
	program: string;
};

export default function QuestionTags({ tags, program }: Props) {
	return (
		<div className="flex flex-wrap gap-2">
			<ProgramTag program={program} />
			{tags.map((tag) => (
				<Badge key={tag} className="p-2" variant="outline">
					{tag}
				</Badge>
			))}
		</div>
	);
}

// src/components/shared/QuestionTags.vue
<script setup lang="ts">
import type { Question } from "@qnaplus/scraper";
import ProgramTag from "./ProgramTag.vue";
const { tags, program } = defineProps<Pick<Question, "tags" | "program">>();
</script>

<template>
    <div class="flex gap-2">
        <ProgramTag :program="program" />
        <Tag v-for="tag in tags">{{ tag }}</Tag>
    </div>
</template>
