// src/components/search/NoResults.vue
<script setup lang="ts">

</script>

<template>
    <Card class="prose text-center max-w-none p-3 rounded-md!">
        <template #header>
            <div class="text-7xl font-bold">{{ ":(" }}</div>
        </template>
        <template #content>
            (no results)
        </template>
    </Card>
</template>

// src/components/search/NoResults.tsx
import { Card } from "@heroui/react";

export default function NoResults() {
	return (
		<Card.Root className="text-center p-3 max-w-none rounded-md">
			<Card.Header>
				<h2 className="text-5xl font-bold">:(</h2>
			</Card.Header>
			<Card.Content>
				<p>(no results)</p>
			</Card.Content>
		</Card.Root>
	);
}
