// src/components/search/QuestionCard.tsx
import { Card, CardContent, CardFooter, CardHeader } from "@/components/ui/card";
import type { Question } from "@qnaplus/scraper";
import { KeyboardEvent } from "react";
import { useSearchStore } from "@/stores/search";
import QuestionDetails from "@/components/question/QuestionDetails";
import QuestionTags from "@/components/question/QuestionTags";

type Props = {
    question: Question;
};

const FADE_MASK =
    "linear-gradient(to bottom, rgba(0,0,0,1) 70%, rgba(0,0,0,0) 100%)";

export default function QuestionCard({ question }: Props) {
    const openQuestion = useSearchStore((s) => s.openQuestion);
    const open = () => openQuestion(question);
    const onKeyDown = (e: KeyboardEvent<HTMLDivElement>) => {
        if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            open();
        }
    };
    return (
        <Card
            className="border flex flex-col cursor-pointer transition-colors hover:bg-muted ring-0 focus-visible:outline-2 focus-visible:outline-ring mb-2 w-full"
            onClick={open}
            onKeyDown={onKeyDown}
        >
            <CardHeader>
                <div className="font-medium text-lg">{question.title}</div>
                <QuestionDetails question={question} />
            </CardHeader>
            <CardContent
                className="prose dark:prose-invert max-w-none min-h-40 max-h-40 overflow-hidden w-full"
                style={{
                    WebkitMaskImage: FADE_MASK,
                    maskImage: FADE_MASK,
                }}
            >
                    <div
                        // biome-ignore lint/security/noDangerouslySetInnerHtml: sanitized via sanitize-html during minisearch load
                        dangerouslySetInnerHTML={{ __html: question.questionRaw }}
                    />
            </CardContent>
            <CardFooter className="flex flex-col items-stretch gap-2">
                <QuestionTags tags={question.tags} program={question.program} />
            </CardFooter>
        </Card>
    );
}

// src/components/search/QuestionCard.vue
<script setup lang="ts">
import type { Question } from "@qnaplus/scraper";
import { renderQuestion } from "../../rendering";
import QuestionDetails from "../shared/QuestionDetails.vue";
import QuestionTags from "../shared/QuestionTags.vue";

const question = defineProps<Question>();
const { questionContent, answerContent } = renderQuestion(question, {
	limit: 75,
});
const emit = defineEmits<{
	"read-more": [question: Question];
}>();

const onActivate = () => emit("read-more", question);
const onKeydown = (e: KeyboardEvent) => {
	if (e.key === "Enter" || e.key === " ") {
		e.preventDefault();
		onActivate();
	}
};
</script>

<template>
    <!-- TODO:
        make the webkit-mask work with light mode theming
    -->
    <UCard
        :title="title"
        variant="subtle"
        role="button"
        tabindex="0"
        :aria-label="`Read more: ${title}`"
        class="max-w-none border-1 border-[var(--ui-border)] mb-3 cursor-pointer transition-colors hover:bg-muted/30 ring-0"
        @click="onActivate"
        @keydown="onKeydown"
    >
        <template #header>
            <div class="flex flex-col gap-1">
                <span class="text-base font-medium">{{ title }}</span>
                <question-details :question="question" />
            </div>
        </template>
        <div class="masked-content max-h-48 overflow-hidden text-muted break-words">
            <div class="flex flex-col gap-2">
                <div>
                    <component :is="component.node" v-bind="component.props" v-for="component in questionContent" />
                </div>
                <div v-if="answered">
                    <span class="font-medium">Answer</span>
                    <component :is="component.node" v-bind="component.props" v-for="component in answerContent" />
                </div>
            </div>
        </div>
        <template #footer>
            <QuestionTags :tags="question.tags" :program="question.program" />
        </template>
    </UCard>
</template>

<style scoped>
.masked-content {
    -webkit-mask-image: linear-gradient(to bottom, rgba(0, 0, 0, 1) 70%, rgba(0, 0, 0, 0) 100%);
    mask-image: linear-gradient(to bottom, rgba(0, 0, 0, 1) 70%, rgba(0, 0, 0, 0) 100%);
}
</style>
