// src/components/search/SearchOptions.vue
<script setup lang="ts">
import type { AutoCompleteCompleteEvent } from "primevue/autocomplete";
import { computed, ref, toRef } from "vue";
import { VueDraggable } from "vue-draggable-plus";
import type { Option } from "../../composable/types";
import {
    getAuthorSuggestions,
    getTagSuggestions,
} from "../../composable/useSearch";
import {
    type SearchFilterOptions,
    questionStateOptions,
} from "../../composable/useSearchFilter";
import {
    type SearchSortOptions,
    type SortOptions,
    sortOptionsList,
    sortOrderList,
} from "../../composable/useSort";

const props = defineProps<{
    filterOptions: SearchFilterOptions;
    sortOptions: SearchSortOptions;
}>();

const remainingAdvancedOptions = computed(() => {
    return sortOptionsList.filter(
        (sortOption) =>
            !props.sortOptions.advanced.find(
                (selectedSortOption) => sortOption.value === selectedSortOption.value,
            ),
    );
});

const updateSelectedAdvancedOption = (value: Option<SortOptions>) => {
    props.sortOptions.advanced.push({ ...value, asc: sortOrderList[0] });
};

const removeSelectedAdvancedOption = (index: number) => {
    props.sortOptions.advanced.splice(index, 1);
};

const authorSuggestions = ref<string[]>([]);
const updateAuthorSuggestions = () => {
    authorSuggestions.value = getAuthorSuggestions(
        props.filterOptions.filters.author,
    );
};

const tagSuggestions = ref<string[]>([]);
const updateTagSuggestions = (e: AutoCompleteCompleteEvent) => {
    tagSuggestions.value = getTagSuggestions(e.query);
};
</script>

<template>

    <Accordion :value="undefined">
        <AccordionPanel :value="0">
            <AccordionHeader>Search Options</AccordionHeader>
            <AccordionContent>
                <Tabs value="0">
                    <TabList>
                        <Tab class="flex gap-3" value="0">Filter
                            <Badge class="ml-2" :value="filterOptions.appliedFilterCount.value" />
                        </Tab>
                        <Tab value="1">Sort</Tab>
                    </TabList>
                    <TabPanels>
                        <TabPanel value="0">
                            <div class="flex flex-col gap-3">
                                <div class="flex flex-wrap gap-3">

                                    <div class="flex flex-wrap gap-3 flex-1">
                                        <div class="m-0 dropdown-flex">
                                            <label for="season">Season</label>
                                            <MultiSelect class="w-full" input-id="season"
                                                v-model="filterOptions.filters.season" placeholder="Season"
                                                :options="filterOptions.seasons" option-label="name" />
                                        </div>
                                        <div class="m-0 dropdown-flex">
                                            <label for="program">Program</label>
                                            <MultiSelect class="w-full" input-id="program"
                                                v-model="filterOptions.filters.program" placeholder="Program"
                                                :options="filterOptions.programs" option-label="name" />
                                        </div>
                                    </div>

                                    <div class="flex flex-1 flex-wrap gap-3">
                                        <div class="m-0 input-flex">
                                            <label for="author">Author</label>
                                            <IconField>
                                                <InputIcon class="pi pi-user" />
                                                <AutoComplete id="author" class="w-full" input-class="w-full"
                                                    v-model="filterOptions.filters.author"
                                                    @complete="updateAuthorSuggestions" :suggestions="authorSuggestions"
                                                    placeholder="Author" />
                                            </IconField>
                                        </div>

                                        <div class="m-0 input-flex">
                                            <label for="Question State">Question State</label>
                                            <SelectButton class="select-button-flex" :allow-empty="false"
                                                v-model="filterOptions.filters.state" :options="questionStateOptions"
                                                option-label="name" aria-labelledby="multiple" />
                                        </div>
                                    </div>
                                </div>

                                <div class="flex flex-wrap gap-3 ">
                                    <div class="flex flex-1 min-w-fit gap-3">
                                        <div class="m-0 flex-1">
                                            <label for="askedBefore">Asked Before</label>
                                            <DatePicker class="w-full" input-id="askedBefore"
                                                v-model="filterOptions.filters.askedBefore" placeholder="Asked Before"
                                                show-icon show-button-bar icon-display="input" />
                                        </div>
                                        <div class="m-0 flex-1">
                                            <label for="askedAfter">Asked After</label>
                                            <DatePicker class="w-full" input-id="askedAfter"
                                                v-model="filterOptions.filters.askedAfter" placeholder="Asked After"
                                                show-icon show-button-bar icon-display="input" />
                                        </div>
                                    </div>
                                    <div class="flex flex-1 min-w-fit gap-3">
                                        <div class="m-0 flex-1">
                                            <label for="answeredBefore" aria-label="Answered Before">Answered
                                                Before</label>
                                            <DatePicker class="w-full" input-id="answeredBefore"
                                                v-model="filterOptions.filters.answeredBefore"
                                                placeholder="Answered Before" show-icon show-button-bar
                                                icon-display="input" />
                                        </div>
                                        <div class="m-0 flex-1">
                                            <label for="answeredAfter" aria-label="Answered After">Answered
                                                After</label>
                                            <DatePicker class="w-full" input-id="answeredAfter"
                                                v-model="filterOptions.filters.answeredAfter"
                                                placeholder="Answered After" show-icon fluid show-button-bar
                                                icon-display="input" />
                                        </div>
                                    </div>
                                </div>

                                <div class="m-0">
                                    <label for="tags">Tags</label>
                                    <InputGroup>
                                        <InputGroupAddon>
                                            <i class="pi pi-tags" aria-label="Tags" />
                                        </InputGroupAddon>
                                        <AutoComplete class="autocomplete-group" multiple input-id="tags"
                                            v-model="filterOptions.filters.tags" aria-label="Tags"
                                            @complete="updateTagSuggestions" :suggestions="tagSuggestions"
                                            placeholder="Tags" />
                                    </InputGroup>
                                </div>
                                <div>
                                    <Button @click="filterOptions.clearFilters()"><b>Reset Filters</b></Button>
                                </div>
                            </div>
                        </TabPanel>
                        <TabPanel value="1">
                            <template #header>
                                <span style="height: 24px">Sort</span>
                            </template>
                            <div class="flex flex-col gap-3">
                                <div class="flex justify-end">
                                    <div class="flex items-center gap-3">
                                        <label for="advanced_toggle">Advanced Sorting</label>
                                        <ToggleSwitch v-model="sortOptions.advancedEnabled"
                                            input-id="advanced_toggle" />
                                    </div>
                                </div>
                                <div class="flex flex-wrap gap-3" v-if="!sortOptions.advancedEnabled">
                                    <div class="flex-1 m-0">
                                        <label for="basic_sort_option">Sort By</label>
                                        <Select class="w-full" input-id="basic_sort_option"
                                            v-model="sortOptions.basic.sort" :options="sortOptionsList"
                                            option-label="name" />
                                    </div>
                                    <div class="flex-1 m-0">
                                        <label for="basic_sort_order">Order</label>
                                        <Select class="w-full" input-id="basic_sort_order"
                                            v-model="sortOptions.basic.asc" :options="sortOrderList"
                                            option-label="name" />
                                    </div>
                                </div>
                                <div class="flex flex-col gap-3" v-else>
                                    <div class="flex-1">
                                        <label for="sort_option">Sort Option</label>
                                        <Select class="w-full" input-id="sort_option"
                                            :options="remainingAdvancedOptions" option-label="name"
                                            @update:model-value="updateSelectedAdvancedOption" />
                                    </div>
                                    <VueDraggable ref="el" v-model="sortOptions.advanced" ghostClass="sort-ghost"
                                        dragClass="sort-drag" :animation="150" handle=".handle">
                                        <div v-for="(option, index) in sortOptions.advanced">
                                            <div class="flex flex-wrap gap-3">
                                                <div class="flex flex-1 items-center">
                                                    <div class="handle cursor-move p-2 pi pi-bars ml-2"></div>
                                                    <span class="">{{ option.name }}</span>
                                                </div>
                                                <div class="flex flex-1 items-center gap-3">
                                                    <div class="flex flex-1 items-center gap-3 m-0">
                                                        <label :for="'advanced_sort_order_' + option.name">Order</label>
                                                        <Select class="flex-1"
                                                            :input-id="'advanced_sort_order_' + option.name"
                                                            v-model="sortOptions.advanced[index].asc"
                                                            :options="sortOrderList" option-label="name" />
                                                    </div>
                                                    <Button class="self-end" type="button" severity="secondary" rounded
                                                        outlined aria-label="Remove Sort" icon="pi pi-times"
                                                        @click="removeSelectedAdvancedOption(index)" />
                                                </div>
                                            </div>
                                            <Divider />
                                        </div>
                                    </VueDraggable>
                                </div>
                            </div>
                        </TabPanel>
                    </TabPanels>
                </Tabs>
            </AccordionContent>
        </AccordionPanel>
    </Accordion>
</template>

<style scoped>
.min-w-fit {
    min-width: fit-content;
}

.select-button-flex {
    display: flex;
}

.dropdown-flex {
    flex: 231.6px
}

.input-flex {
    flex: 170px;
}

.sort-ghost {
    opacity: 0;
}

.border-1 {
    border-width: 1px;
}
</style>

// src/components/search/SearchOptions.tsx
import {
	Accordion,
	Badge,
	Button,
	ComboBox,
	DatePicker,
	Input,
	Label,
	ListBox,
	Select,
	SelectRoot,
	Switch,
	Tabs,
	ToggleButton,
	ToggleButtonGroup,
} from "@heroui/react";
import {
	type CalendarDate,
	getLocalTimeZone,
	parseDate,
} from "@internationalized/date";
import type { Key, ReactNode } from "react";
import { useMemo, useState } from "react";
import {
	getAuthorSuggestions,
	getTagSuggestions,
} from "../../lib/minisearch";
import { useAppDataStore } from "../../stores/appData";
import {
	QuestionStateValue,
	questionStateOptions,
	selectAppliedFilterCount,
	useFilterStore,
} from "../../stores/filters";
import {
	SortOptions,
	sortOptionsList,
	sortOrderList,
	useSortStore,
} from "../../stores/sort";
import AdvancedSortList from "./sort/AdvancedSortList";

const toCalendarDate = (d: Date | null): CalendarDate | null => {
	if (d === null) return null;
	const iso = d.toISOString().slice(0, 10);
	return parseDate(iso);
};

const fromCalendarDate = (d: CalendarDate | null): Date | null => {
	if (d === null) return null;
	return d.toDate(getLocalTimeZone());
};

type LabeledFieldProps = {
	label: string;
	children: ReactNode;
	className?: string;
};

const LabeledField = ({ label, children, className }: LabeledFieldProps) => (
	<div className={`flex flex-col gap-1 ${className ?? ""}`}>
		<Label className="text-sm text-muted">{label}</Label>
		{children}
	</div>
);

export default function SearchOptions() {
	const seasons = useAppDataStore((s) => s.seasons);
	const programs = useAppDataStore((s) => s.programs);

	const filters = useFilterStore((s) => s.filters);
	const setFilter = useFilterStore((s) => s.setFilter);
	const clearFilters = useFilterStore((s) => s.clearFilters);
	const appliedFilterCount = selectAppliedFilterCount(filters);

	const sort = useSortStore((s) => s.sort);
	const setBasicSort = useSortStore((s) => s.setBasicSort);
	const setBasicAsc = useSortStore((s) => s.setBasicAsc);
	const toggleAdvanced = useSortStore((s) => s.toggleAdvanced);
	const addAdvanced = useSortStore((s) => s.addAdvanced);

	const [authorInput, setAuthorInput] = useState(filters.author ?? "");
	const [tagInput, setTagInput] = useState("");

	const authorSuggestions = useMemo(
		() => getAuthorSuggestions(authorInput === "" ? null : authorInput),
		[authorInput],
	);
	const tagSuggestions = useMemo(
		() => getTagSuggestions(tagInput === "" ? undefined : tagInput),
		[tagInput],
	);

	const remainingAdvanced = useMemo(
		() => sortOptionsList.filter((o) => !sort.advanced.find((s) => s.value === o.value)),
		[sort.advanced],
	);

	const onMultiSelectChange =
		<T extends string>(field: "season" | "program") =>
		(keys: Key[]) => {
			setFilter(
				field,
				keys.map((k) => ({ name: String(k) as T, value: String(k) as T })),
			);
		};

	const handleBasicSortChange = (key: Key | null) => {
		if (key === null) return;
		const v = Number(key) as SortOptions;
		const next = sortOptionsList.find((o) => o.value === v);
		if (next) setBasicSort(next);
	};

	const handleBasicOrderChange = (key: Key | null) => {
		if (key === null) return;
		const v = Number(key);
		const next = sortOrderList.find((o) => o.value === v);
		if (next) setBasicAsc(next);
	};

	const handleAddAdvanced = (key: Key | null) => {
		if (key === null) return;
		const v = Number(key) as SortOptions;
		const next = sortOptionsList.find((o) => o.value === v);
		if (next) addAdvanced(next);
	};

	const handleQuestionStateChange = (keys: "all" | Set<Key>) => {
		if (keys === "all") return;
		const first = [...keys][0];
		if (first === undefined) return;
		const v = Number(first) as QuestionStateValue;
		const opt = questionStateOptions.find((o) => o.value === v);
		if (opt) setFilter("state", opt);
	};

	const handleAuthorSelection = (key: Key | null) => {
		const v = key === null ? null : String(key);
		setFilter("author", v);
		setAuthorInput(v ?? "");
	};

	const handleTagSelected = (key: Key | null) => {
		if (key === null) return;
		const v = String(key);
		if (filters.tags.includes(v)) return;
		setFilter("tags", [...filters.tags, v]);
		setTagInput("");
	};

	const removeTag = (tag: string) =>
		setFilter("tags", filters.tags.filter((t) => t !== tag));

	return (
		<Accordion>
			<Accordion.Item id="search-options">
				<Accordion.Heading>
					<Accordion.Trigger>
						<span className="flex-1 text-left font-medium">Search Options</span>
						{appliedFilterCount > 0 && <Badge>{appliedFilterCount}</Badge>}
						<Accordion.Indicator />
					</Accordion.Trigger>
				</Accordion.Heading>
				<Accordion.Panel>
					<Accordion.Body>
						<Tabs defaultSelectedKey="filter" variant="secondary">
							<Tabs.List>
								<Tabs.Tab id="filter">Filter</Tabs.Tab>
								<Tabs.Tab id="sort">Sort</Tabs.Tab>
							</Tabs.List>

							<Tabs.Panel id="filter">
								<div className="flex flex-col gap-3 pt-2">
									<div className="flex flex-wrap gap-2">
										<LabeledField label="Season" className="flex-1 min-w-50">
											<SelectRoot<object, "multiple">
												selectionMode="multiple"
												value={filters.season.map((s) => s.value)}
												onChange={onMultiSelectChange<string>("season")}
											>
												<Select.Trigger>
													<Select.Value>
														{filters.season.length === 0
															? "Season"
															: filters.season.map((s) => s.value).join(", ")}
													</Select.Value>
													<Select.Indicator />
												</Select.Trigger>
												<Select.Popover>
													<ListBox>
														{seasons.map((s) => (
															<ListBox.Item key={s} id={s}>
																{s}
															</ListBox.Item>
														))}
													</ListBox>
												</Select.Popover>
											</SelectRoot>
										</LabeledField>

										<LabeledField label="Program" className="flex-1 min-w-50">
											<SelectRoot<object, "multiple">
												selectionMode="multiple"
												value={filters.program.map((p) => p.value)}
												onChange={onMultiSelectChange<string>("program")}
											>
												<Select.Trigger>
													<Select.Value>
														{filters.program.length === 0
															? "Program"
															: filters.program.map((p) => p.value).join(", ")}
													</Select.Value>
													<Select.Indicator />
												</Select.Trigger>
												<Select.Popover>
													<ListBox>
														{programs.map((p) => (
															<ListBox.Item key={p} id={p}>
																{p}
															</ListBox.Item>
														))}
													</ListBox>
												</Select.Popover>
											</SelectRoot>
										</LabeledField>
									</div>

									<div className="flex flex-wrap gap-2">
										<LabeledField label="Author" className="flex-1 min-w-42">
											<ComboBox
												inputValue={authorInput}
												onInputChange={setAuthorInput}
												onSelectionChange={handleAuthorSelection}
												onBlur={() =>
													setFilter("author", authorInput === "" ? null : authorInput)
												}
											>
												<ComboBox.InputGroup>
													<Input placeholder="Author" />
													<ComboBox.Trigger />
												</ComboBox.InputGroup>
												<ComboBox.Popover>
													<ListBox>
														{authorSuggestions.map((a) => (
															<ListBox.Item key={a} id={a}>
																{a}
															</ListBox.Item>
														))}
													</ListBox>
												</ComboBox.Popover>
											</ComboBox>
										</LabeledField>

										<LabeledField label="Question State" className="flex-1 min-w-42">
											<ToggleButtonGroup
												selectionMode="single"
												selectedKeys={new Set([String(filters.state.value)])}
												onSelectionChange={handleQuestionStateChange}
												isDetached={false}
											>
												{questionStateOptions.map((o) => (
													<ToggleButton key={o.value} id={String(o.value)}>
														{o.name}
													</ToggleButton>
												))}
											</ToggleButtonGroup>
										</LabeledField>
									</div>

									<div className="flex flex-wrap gap-2">
										<LabeledField label="Asked Before" className="flex-1 min-w-37">
											<DatePicker
												value={toCalendarDate(filters.askedBefore)}
												onChange={(d) =>
													setFilter("askedBefore", fromCalendarDate(d))
												}
											/>
										</LabeledField>
										<LabeledField label="Asked After" className="flex-1 min-w-37">
											<DatePicker
												value={toCalendarDate(filters.askedAfter)}
												onChange={(d) =>
													setFilter("askedAfter", fromCalendarDate(d))
												}
											/>
										</LabeledField>
										<LabeledField label="Answered Before" className="flex-1 min-w-37">
											<DatePicker
												value={toCalendarDate(filters.answeredBefore)}
												onChange={(d) =>
													setFilter("answeredBefore", fromCalendarDate(d))
												}
											/>
										</LabeledField>
										<LabeledField label="Answered After" className="flex-1 min-w-37">
											<DatePicker
												value={toCalendarDate(filters.answeredAfter)}
												onChange={(d) =>
													setFilter("answeredAfter", fromCalendarDate(d))
												}
											/>
										</LabeledField>
									</div>

									<LabeledField label="Tags">
										<ComboBox
											inputValue={tagInput}
											onInputChange={setTagInput}
											onSelectionChange={handleTagSelected}
										>
											<ComboBox.InputGroup>
												<Input placeholder="Add a tag…" />
												<ComboBox.Trigger />
											</ComboBox.InputGroup>
											<ComboBox.Popover>
												<ListBox>
													{tagSuggestions.map((t) => (
														<ListBox.Item key={t} id={t}>
															{t}
														</ListBox.Item>
													))}
												</ListBox>
											</ComboBox.Popover>
										</ComboBox>
										{filters.tags.length > 0 && (
											<div className="flex flex-wrap gap-2 mt-2">
												{filters.tags.map((tag) => (
													<Button
														key={tag}
														size="sm"
														variant="outline"
														onPress={() => removeTag(tag)}
													>
														{tag} ✕
													</Button>
												))}
											</div>
										)}
									</LabeledField>

									<div>
										<Button size="sm" variant="outline" onPress={clearFilters}>
											Reset Filters
										</Button>
									</div>
								</div>
							</Tabs.Panel>

							<Tabs.Panel id="sort">
								<div className="flex flex-col gap-3 pt-2">
									<div className="flex justify-end">
										<Switch
											isSelected={sort.advancedEnabled}
											onChange={toggleAdvanced}
										>
											<Switch.Control>
												<Switch.Thumb />
											</Switch.Control>
											<Switch.Content className="text-sm text-muted">
												Advanced Sorting
											</Switch.Content>
										</Switch>
									</div>

									{!sort.advancedEnabled ? (
										<div className="flex flex-wrap gap-2">
											<LabeledField label="Sort By" className="flex-1">
												<Select.Root
													selectedKey={String(sort.basic.sort.value)}
													onSelectionChange={handleBasicSortChange}
												>
													<Select.Trigger>
														<Select.Value>{sort.basic.sort.name}</Select.Value>
														<Select.Indicator />
													</Select.Trigger>
													<Select.Popover>
														<ListBox>
															{sortOptionsList.map((o) => (
																<ListBox.Item key={o.value} id={String(o.value)}>
																	{o.name}
																</ListBox.Item>
															))}
														</ListBox>
													</Select.Popover>
												</Select.Root>
											</LabeledField>
											<LabeledField label="Order" className="flex-1">
												<Select.Root
													selectedKey={String(sort.basic.asc.value)}
													onSelectionChange={handleBasicOrderChange}
												>
													<Select.Trigger>
														<Select.Value>{sort.basic.asc.name}</Select.Value>
														<Select.Indicator />
													</Select.Trigger>
													<Select.Popover>
														<ListBox>
															{sortOrderList.map((o) => (
																<ListBox.Item key={o.value} id={String(o.value)}>
																	{o.name}
																</ListBox.Item>
															))}
														</ListBox>
													</Select.Popover>
												</Select.Root>
											</LabeledField>
										</div>
									) : (
										<div className="flex flex-col gap-3">
											<LabeledField label="Add Sort Option">
												<Select.Root
													selectedKey={null}
													onSelectionChange={handleAddAdvanced}
												>
													<Select.Trigger>
														<Select.Value>Add…</Select.Value>
														<Select.Indicator />
													</Select.Trigger>
													<Select.Popover>
														<ListBox>
															{remainingAdvanced.map((o) => (
																<ListBox.Item key={o.value} id={String(o.value)}>
																	{o.name}
																</ListBox.Item>
															))}
														</ListBox>
													</Select.Popover>
												</Select.Root>
											</LabeledField>
											<AdvancedSortList />
										</div>
									)}
								</div>
							</Tabs.Panel>
						</Tabs>
					</Accordion.Body>
				</Accordion.Panel>
			</Accordion.Item>
		</Accordion>
	);
}
