// src/components/question/QuestionDetails.tsx
import type { Question } from "@qnaplus/scraper";
import { IconCheck } from "@tabler/icons-react";
import { isEmpty } from "../../util/strings";

type Props = {
	question: Question;
};

export default function QuestionDetails({ question }: Props) {
	const answeredLabel = question.answered ? "Answered" : "Unanswered";
	return (
		<div className="flex flex-col xl:flex-row items-start xl:items-center justify-between gap-2">
			<div className="flex flex-wrap items-center gap-2 text-muted">
				{!isEmpty(question.author) && <span>{question.author}</span>}
				{!isEmpty(question.askedTimestamp) && (
					<>
						<span>·</span>
						<span>{question.askedTimestamp}</span>
					</>
				)}
			</div>
			<div className="flex items-center gap-1.5">
				{question.answered ? (
					<span className="inline-flex items-center gap-1 text-green-400 bg-green-500/10 px-1.5 py-0.5 rounded-md text-sm">
						<IconCheck size={14} />
						<span>{answeredLabel}</span>
					</span>
				) : (
					<span className="text-sm text-muted">{answeredLabel}</span>
				)}
			</div>
		</div>
	);
}

// src/components/question/QuestionDetails.vue
<script setup lang="ts">
import type { Question } from "@qnaplus/scraper";
import { isEmpty } from "../../util/strings";

const { question } = defineProps<{ question: Question }>();
const { author, askedTimestamp, answered, answeredTimestamp } = question;
</script>

<template>
    <div class="flex justify-between">
        <span><b>{{ author }}</b> on <b>{{ askedTimestamp }}</b></span>
        <span v-if="answered" class="flex gap-2 items-center text-green-500">
            <i class="pi pi-check " />
            <span v-if="!isEmpty(answeredTimestamp)">Answered on <b>{{ answeredTimestamp }}</b></span>
            <span v-else>Answered</span>
        </span>
        <span v-else class="text-muted-color">Unanswered</span>
    </div>
</template>
