// src/App.tsx
import { IconLoader2 } from "@tabler/icons-react";
import { useEffect, useState } from "react";
import { Route, Switch } from "wouter";
import { database, getAppData, setupDatabase } from "./database";
import { useMinisearchLoader } from "./hooks/useMinisearchLoader";
import SearchPage from "./pages/SearchPage";
import QuestionPage from "./pages/QuestionPage";
import { useAppDataStore } from "./stores/appData";

const appName = import.meta.env.VITE_APP_NAME;

export default function App() {
	const [loading, setLoading] = useState(true);
	const setAppData = useAppDataStore((s) => s.setAppData);
	const loadMinisearch = useMinisearchLoader();

	useEffect(() => {
		const startup = async () => {
			try {
				await setupDatabase();
				const data = await getAppData();
				if (data !== undefined) {
					setAppData({ seasons: data.seasons, programs: data.programs });
				}
				const questions = await database.questions.toArray();
				await loadMinisearch(questions);
			} catch (e) {
				console.error(e);
			} finally {
				setLoading(false);
			}
		};
		void startup();
	}, [setAppData, loadMinisearch]);

	if (loading) {
		return (
			<div className="h-screen-mobile flex items-center justify-center gap-4">
				<h1 className="text-xl font-semibold">{appName}</h1>
				<IconLoader2 size={32} className="animate-spin" />
			</div>
		);
	}

	return (
		<Switch>
			<Route path="/" component={SearchPage} />
			<Route path="/:id" component={QuestionPage} />
		</Switch>
	);
}

// src/App.vue
<script setup lang="ts">
import { provide, ref } from "vue";
import { loadMinisearch } from "./composable/useSearch";
import {
	type QnaplusAppData,
	database,
	getAppData,
	setupDatabase,
} from "./database";

const loading = ref<boolean>(true);
const appdata = ref<QnaplusAppData>();
provide("appdata", appdata);

const appname = import.meta.env.VITE_APP_NAME;

const startup = async () => {
	try {
		await setupDatabase();

		const data = await getAppData();
		appdata.value = data;

		const questions = await database.questions.toArray();
		await loadMinisearch(questions);
	} catch (e) {
		console.error(e);
	} finally {
		loading.value = false;
	}
};

startup();
</script>

<template>
	<UApp>
		<div v-if="loading" class="flex flex-row h-screen-mobile justify-center items-center gap-x-4">
			<h1 class="text-xl font-semibold">{{ appname }}</h1>
			<UIcon name="i-lucide-loader-circle" class="size-10 animate-spin text-primary" />
		</div>
		<UMain v-else>
			<Suspense>
				<router-view class="w-full"></router-view>
			</Suspense>
		</UMain>
	</UApp>
</template>

<style>
@import "./styles.css";
</style>
